// Generated by gencpp from file nav_apf_smach/DriveToPoseFeedback.msg
// DO NOT EDIT!


#ifndef NAV_APF_SMACH_MESSAGE_DRIVETOPOSEFEEDBACK_H
#define NAV_APF_SMACH_MESSAGE_DRIVETOPOSEFEEDBACK_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace nav_apf_smach
{
template <class ContainerAllocator>
struct DriveToPoseFeedback_
{
  typedef DriveToPoseFeedback_<ContainerAllocator> Type;

  DriveToPoseFeedback_()
    : remaining_distance(0.0)  {
    }
  DriveToPoseFeedback_(const ContainerAllocator& _alloc)
    : remaining_distance(0.0)  {
  (void)_alloc;
    }



   typedef float _remaining_distance_type;
  _remaining_distance_type remaining_distance;





  typedef boost::shared_ptr< ::nav_apf_smach::DriveToPoseFeedback_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::nav_apf_smach::DriveToPoseFeedback_<ContainerAllocator> const> ConstPtr;

}; // struct DriveToPoseFeedback_

typedef ::nav_apf_smach::DriveToPoseFeedback_<std::allocator<void> > DriveToPoseFeedback;

typedef boost::shared_ptr< ::nav_apf_smach::DriveToPoseFeedback > DriveToPoseFeedbackPtr;
typedef boost::shared_ptr< ::nav_apf_smach::DriveToPoseFeedback const> DriveToPoseFeedbackConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::nav_apf_smach::DriveToPoseFeedback_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::nav_apf_smach::DriveToPoseFeedback_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::nav_apf_smach::DriveToPoseFeedback_<ContainerAllocator1> & lhs, const ::nav_apf_smach::DriveToPoseFeedback_<ContainerAllocator2> & rhs)
{
  return lhs.remaining_distance == rhs.remaining_distance;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::nav_apf_smach::DriveToPoseFeedback_<ContainerAllocator1> & lhs, const ::nav_apf_smach::DriveToPoseFeedback_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace nav_apf_smach

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::nav_apf_smach::DriveToPoseFeedback_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::nav_apf_smach::DriveToPoseFeedback_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::nav_apf_smach::DriveToPoseFeedback_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::nav_apf_smach::DriveToPoseFeedback_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::nav_apf_smach::DriveToPoseFeedback_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::nav_apf_smach::DriveToPoseFeedback_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::nav_apf_smach::DriveToPoseFeedback_<ContainerAllocator> >
{
  static const char* value()
  {
    return "af85e6a5c9030f385c968a48eaafb15c";
  }

  static const char* value(const ::nav_apf_smach::DriveToPoseFeedback_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xaf85e6a5c9030f38ULL;
  static const uint64_t static_value2 = 0x5c968a48eaafb15cULL;
};

template<class ContainerAllocator>
struct DataType< ::nav_apf_smach::DriveToPoseFeedback_<ContainerAllocator> >
{
  static const char* value()
  {
    return "nav_apf_smach/DriveToPoseFeedback";
  }

  static const char* value(const ::nav_apf_smach::DriveToPoseFeedback_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::nav_apf_smach::DriveToPoseFeedback_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n"
"# Feedback\n"
"float32 remaining_distance\n"
"\n"
;
  }

  static const char* value(const ::nav_apf_smach::DriveToPoseFeedback_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::nav_apf_smach::DriveToPoseFeedback_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.remaining_distance);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct DriveToPoseFeedback_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::nav_apf_smach::DriveToPoseFeedback_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::nav_apf_smach::DriveToPoseFeedback_<ContainerAllocator>& v)
  {
    s << indent << "remaining_distance: ";
    Printer<float>::stream(s, indent + "  ", v.remaining_distance);
  }
};

} // namespace message_operations
} // namespace ros

#endif // NAV_APF_SMACH_MESSAGE_DRIVETOPOSEFEEDBACK_H
