// Generated by gencpp from file nav_apf_smach/NextWaypointResult.msg
// DO NOT EDIT!


#ifndef NAV_APF_SMACH_MESSAGE_NEXTWAYPOINTRESULT_H
#define NAV_APF_SMACH_MESSAGE_NEXTWAYPOINTRESULT_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <geometry_msgs/PoseStamped.h>

namespace nav_apf_smach
{
template <class ContainerAllocator>
struct NextWaypointResult_
{
  typedef NextWaypointResult_<ContainerAllocator> Type;

  NextWaypointResult_()
    : next_waypoint()
    , goal_reached(false)  {
    }
  NextWaypointResult_(const ContainerAllocator& _alloc)
    : next_waypoint(_alloc)
    , goal_reached(false)  {
  (void)_alloc;
    }



   typedef  ::geometry_msgs::PoseStamped_<ContainerAllocator>  _next_waypoint_type;
  _next_waypoint_type next_waypoint;

   typedef uint8_t _goal_reached_type;
  _goal_reached_type goal_reached;





  typedef boost::shared_ptr< ::nav_apf_smach::NextWaypointResult_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::nav_apf_smach::NextWaypointResult_<ContainerAllocator> const> ConstPtr;

}; // struct NextWaypointResult_

typedef ::nav_apf_smach::NextWaypointResult_<std::allocator<void> > NextWaypointResult;

typedef boost::shared_ptr< ::nav_apf_smach::NextWaypointResult > NextWaypointResultPtr;
typedef boost::shared_ptr< ::nav_apf_smach::NextWaypointResult const> NextWaypointResultConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::nav_apf_smach::NextWaypointResult_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::nav_apf_smach::NextWaypointResult_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::nav_apf_smach::NextWaypointResult_<ContainerAllocator1> & lhs, const ::nav_apf_smach::NextWaypointResult_<ContainerAllocator2> & rhs)
{
  return lhs.next_waypoint == rhs.next_waypoint &&
    lhs.goal_reached == rhs.goal_reached;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::nav_apf_smach::NextWaypointResult_<ContainerAllocator1> & lhs, const ::nav_apf_smach::NextWaypointResult_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace nav_apf_smach

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::nav_apf_smach::NextWaypointResult_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::nav_apf_smach::NextWaypointResult_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::nav_apf_smach::NextWaypointResult_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::nav_apf_smach::NextWaypointResult_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::nav_apf_smach::NextWaypointResult_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::nav_apf_smach::NextWaypointResult_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::nav_apf_smach::NextWaypointResult_<ContainerAllocator> >
{
  static const char* value()
  {
    return "dc767de33709a7aaa6304200bd40705d";
  }

  static const char* value(const ::nav_apf_smach::NextWaypointResult_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xdc767de33709a7aaULL;
  static const uint64_t static_value2 = 0xa6304200bd40705dULL;
};

template<class ContainerAllocator>
struct DataType< ::nav_apf_smach::NextWaypointResult_<ContainerAllocator> >
{
  static const char* value()
  {
    return "nav_apf_smach/NextWaypointResult";
  }

  static const char* value(const ::nav_apf_smach::NextWaypointResult_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::nav_apf_smach::NextWaypointResult_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n"
"# Result\n"
"geometry_msgs/PoseStamped next_waypoint\n"
"bool goal_reached\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/PoseStamped\n"
"# A Pose with reference coordinate frame and timestamp\n"
"Header header\n"
"Pose pose\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Pose\n"
"# A representation of pose in free space, composed of position and orientation. \n"
"Point position\n"
"Quaternion orientation\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Point\n"
"# This contains the position of a point in free space\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Quaternion\n"
"# This represents an orientation in free space in quaternion form.\n"
"\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
"float64 w\n"
;
  }

  static const char* value(const ::nav_apf_smach::NextWaypointResult_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::nav_apf_smach::NextWaypointResult_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.next_waypoint);
      stream.next(m.goal_reached);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct NextWaypointResult_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::nav_apf_smach::NextWaypointResult_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::nav_apf_smach::NextWaypointResult_<ContainerAllocator>& v)
  {
    s << indent << "next_waypoint: ";
    s << std::endl;
    Printer< ::geometry_msgs::PoseStamped_<ContainerAllocator> >::stream(s, indent + "  ", v.next_waypoint);
    s << indent << "goal_reached: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.goal_reached);
  }
};

} // namespace message_operations
} // namespace ros

#endif // NAV_APF_SMACH_MESSAGE_NEXTWAYPOINTRESULT_H
