; Auto-generated. Do not edit!


(cl:in-package nav_apf_smach-msg)


;//! \htmlinclude DriveToPoseFeedback.msg.html

(cl:defclass <DriveToPoseFeedback> (roslisp-msg-protocol:ros-message)
  ((remaining_distance
    :reader remaining_distance
    :initarg :remaining_distance
    :type cl:float
    :initform 0.0))
)

(cl:defclass DriveToPoseFeedback (<DriveToPoseFeedback>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <DriveToPoseFeedback>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'DriveToPoseFeedback)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name nav_apf_smach-msg:<DriveToPoseFeedback> is deprecated: use nav_apf_smach-msg:DriveToPoseFeedback instead.")))

(cl:ensure-generic-function 'remaining_distance-val :lambda-list '(m))
(cl:defmethod remaining_distance-val ((m <DriveToPoseFeedback>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader nav_apf_smach-msg:remaining_distance-val is deprecated.  Use nav_apf_smach-msg:remaining_distance instead.")
  (remaining_distance m))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <DriveToPoseFeedback>) ostream)
  "Serializes a message object of type '<DriveToPoseFeedback>"
  (cl:let ((bits (roslisp-utils:encode-single-float-bits (cl:slot-value msg 'remaining_distance))))
    (cl:write-byte (cl:ldb (cl:byte 8 0) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 8) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 16) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 24) bits) ostream))
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <DriveToPoseFeedback>) istream)
  "Deserializes a message object of type '<DriveToPoseFeedback>"
    (cl:let ((bits 0))
      (cl:setf (cl:ldb (cl:byte 8 0) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 8) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 16) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 24) bits) (cl:read-byte istream))
    (cl:setf (cl:slot-value msg 'remaining_distance) (roslisp-utils:decode-single-float-bits bits)))
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<DriveToPoseFeedback>)))
  "Returns string type for a message object of type '<DriveToPoseFeedback>"
  "nav_apf_smach/DriveToPoseFeedback")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'DriveToPoseFeedback)))
  "Returns string type for a message object of type 'DriveToPoseFeedback"
  "nav_apf_smach/DriveToPoseFeedback")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<DriveToPoseFeedback>)))
  "Returns md5sum for a message object of type '<DriveToPoseFeedback>"
  "af85e6a5c9030f385c968a48eaafb15c")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'DriveToPoseFeedback)))
  "Returns md5sum for a message object of type 'DriveToPoseFeedback"
  "af85e6a5c9030f385c968a48eaafb15c")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<DriveToPoseFeedback>)))
  "Returns full string definition for message of type '<DriveToPoseFeedback>"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%# Feedback~%float32 remaining_distance~%~%~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'DriveToPoseFeedback)))
  "Returns full string definition for message of type 'DriveToPoseFeedback"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%# Feedback~%float32 remaining_distance~%~%~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <DriveToPoseFeedback>))
  (cl:+ 0
     4
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <DriveToPoseFeedback>))
  "Converts a ROS message object to a list"
  (cl:list 'DriveToPoseFeedback
    (cl:cons ':remaining_distance (remaining_distance msg))
))
