; Auto-generated. Do not edit!


(cl:in-package nav_apf_smach-msg)


;//! \htmlinclude DriveToPoseGoal.msg.html

(cl:defclass <DriveToPoseGoal> (roslisp-msg-protocol:ros-message)
  ((target
    :reader target
    :initarg :target
    :type geometry_msgs-msg:PoseStamped
    :initform (cl:make-instance 'geometry_msgs-msg:PoseStamped)))
)

(cl:defclass DriveToPoseGoal (<DriveToPoseGoal>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <DriveToPoseGoal>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'DriveToPoseGoal)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name nav_apf_smach-msg:<DriveToPoseGoal> is deprecated: use nav_apf_smach-msg:DriveToPoseGoal instead.")))

(cl:ensure-generic-function 'target-val :lambda-list '(m))
(cl:defmethod target-val ((m <DriveToPoseGoal>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader nav_apf_smach-msg:target-val is deprecated.  Use nav_apf_smach-msg:target instead.")
  (target m))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <DriveToPoseGoal>) ostream)
  "Serializes a message object of type '<DriveToPoseGoal>"
  (roslisp-msg-protocol:serialize (cl:slot-value msg 'target) ostream)
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <DriveToPoseGoal>) istream)
  "Deserializes a message object of type '<DriveToPoseGoal>"
  (roslisp-msg-protocol:deserialize (cl:slot-value msg 'target) istream)
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<DriveToPoseGoal>)))
  "Returns string type for a message object of type '<DriveToPoseGoal>"
  "nav_apf_smach/DriveToPoseGoal")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'DriveToPoseGoal)))
  "Returns string type for a message object of type 'DriveToPoseGoal"
  "nav_apf_smach/DriveToPoseGoal")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<DriveToPoseGoal>)))
  "Returns md5sum for a message object of type '<DriveToPoseGoal>"
  "8ba8aeef25187f3dc987f3a87f890b3a")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'DriveToPoseGoal)))
  "Returns md5sum for a message object of type 'DriveToPoseGoal"
  "8ba8aeef25187f3dc987f3a87f890b3a")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<DriveToPoseGoal>)))
  "Returns full string definition for message of type '<DriveToPoseGoal>"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%# Goal: pose a la que moverse~%geometry_msgs/PoseStamped target~%~%================================================================================~%MSG: geometry_msgs/PoseStamped~%# A Pose with reference coordinate frame and timestamp~%Header header~%Pose pose~%~%================================================================================~%MSG: std_msgs/Header~%# Standard metadata for higher-level stamped data types.~%# This is generally used to communicate timestamped data ~%# in a particular coordinate frame.~%# ~%# sequence ID: consecutively increasing ID ~%uint32 seq~%#Two-integer timestamp that is expressed as:~%# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')~%# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')~%# time-handling sugar is provided by the client library~%time stamp~%#Frame this data is associated with~%string frame_id~%~%================================================================================~%MSG: geometry_msgs/Pose~%# A representation of pose in free space, composed of position and orientation. ~%Point position~%Quaternion orientation~%~%================================================================================~%MSG: geometry_msgs/Point~%# This contains the position of a point in free space~%float64 x~%float64 y~%float64 z~%~%================================================================================~%MSG: geometry_msgs/Quaternion~%# This represents an orientation in free space in quaternion form.~%~%float64 x~%float64 y~%float64 z~%float64 w~%~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'DriveToPoseGoal)))
  "Returns full string definition for message of type 'DriveToPoseGoal"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%# Goal: pose a la que moverse~%geometry_msgs/PoseStamped target~%~%================================================================================~%MSG: geometry_msgs/PoseStamped~%# A Pose with reference coordinate frame and timestamp~%Header header~%Pose pose~%~%================================================================================~%MSG: std_msgs/Header~%# Standard metadata for higher-level stamped data types.~%# This is generally used to communicate timestamped data ~%# in a particular coordinate frame.~%# ~%# sequence ID: consecutively increasing ID ~%uint32 seq~%#Two-integer timestamp that is expressed as:~%# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')~%# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')~%# time-handling sugar is provided by the client library~%time stamp~%#Frame this data is associated with~%string frame_id~%~%================================================================================~%MSG: geometry_msgs/Pose~%# A representation of pose in free space, composed of position and orientation. ~%Point position~%Quaternion orientation~%~%================================================================================~%MSG: geometry_msgs/Point~%# This contains the position of a point in free space~%float64 x~%float64 y~%float64 z~%~%================================================================================~%MSG: geometry_msgs/Quaternion~%# This represents an orientation in free space in quaternion form.~%~%float64 x~%float64 y~%float64 z~%float64 w~%~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <DriveToPoseGoal>))
  (cl:+ 0
     (roslisp-msg-protocol:serialization-length (cl:slot-value msg 'target))
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <DriveToPoseGoal>))
  "Converts a ROS message object to a list"
  (cl:list 'DriveToPoseGoal
    (cl:cons ':target (target msg))
))
