; Auto-generated. Do not edit!


(cl:in-package nav_apf_smach-msg)


;//! \htmlinclude DriveToPoseResult.msg.html

(cl:defclass <DriveToPoseResult> (roslisp-msg-protocol:ros-message)
  ((arrived
    :reader arrived
    :initarg :arrived
    :type cl:boolean
    :initform cl:nil))
)

(cl:defclass DriveToPoseResult (<DriveToPoseResult>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <DriveToPoseResult>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'DriveToPoseResult)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name nav_apf_smach-msg:<DriveToPoseResult> is deprecated: use nav_apf_smach-msg:DriveToPoseResult instead.")))

(cl:ensure-generic-function 'arrived-val :lambda-list '(m))
(cl:defmethod arrived-val ((m <DriveToPoseResult>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader nav_apf_smach-msg:arrived-val is deprecated.  Use nav_apf_smach-msg:arrived instead.")
  (arrived m))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <DriveToPoseResult>) ostream)
  "Serializes a message object of type '<DriveToPoseResult>"
  (cl:write-byte (cl:ldb (cl:byte 8 0) (cl:if (cl:slot-value msg 'arrived) 1 0)) ostream)
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <DriveToPoseResult>) istream)
  "Deserializes a message object of type '<DriveToPoseResult>"
    (cl:setf (cl:slot-value msg 'arrived) (cl:not (cl:zerop (cl:read-byte istream))))
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<DriveToPoseResult>)))
  "Returns string type for a message object of type '<DriveToPoseResult>"
  "nav_apf_smach/DriveToPoseResult")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'DriveToPoseResult)))
  "Returns string type for a message object of type 'DriveToPoseResult"
  "nav_apf_smach/DriveToPoseResult")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<DriveToPoseResult>)))
  "Returns md5sum for a message object of type '<DriveToPoseResult>"
  "ea115e3ceb83b7b5fbcc7f283be1718c")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'DriveToPoseResult)))
  "Returns md5sum for a message object of type 'DriveToPoseResult"
  "ea115e3ceb83b7b5fbcc7f283be1718c")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<DriveToPoseResult>)))
  "Returns full string definition for message of type '<DriveToPoseResult>"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%# Result~%bool arrived~%~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'DriveToPoseResult)))
  "Returns full string definition for message of type 'DriveToPoseResult"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%# Result~%bool arrived~%~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <DriveToPoseResult>))
  (cl:+ 0
     1
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <DriveToPoseResult>))
  "Converts a ROS message object to a list"
  (cl:list 'DriveToPoseResult
    (cl:cons ':arrived (arrived msg))
))
