; Auto-generated. Do not edit!


(cl:in-package nav_apf_smach-msg)


;//! \htmlinclude NextWaypointResult.msg.html

(cl:defclass <NextWaypointResult> (roslisp-msg-protocol:ros-message)
  ((next_waypoint
    :reader next_waypoint
    :initarg :next_waypoint
    :type geometry_msgs-msg:PoseStamped
    :initform (cl:make-instance 'geometry_msgs-msg:PoseStamped))
   (goal_reached
    :reader goal_reached
    :initarg :goal_reached
    :type cl:boolean
    :initform cl:nil))
)

(cl:defclass NextWaypointResult (<NextWaypointResult>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <NextWaypointResult>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'NextWaypointResult)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name nav_apf_smach-msg:<NextWaypointResult> is deprecated: use nav_apf_smach-msg:NextWaypointResult instead.")))

(cl:ensure-generic-function 'next_waypoint-val :lambda-list '(m))
(cl:defmethod next_waypoint-val ((m <NextWaypointResult>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader nav_apf_smach-msg:next_waypoint-val is deprecated.  Use nav_apf_smach-msg:next_waypoint instead.")
  (next_waypoint m))

(cl:ensure-generic-function 'goal_reached-val :lambda-list '(m))
(cl:defmethod goal_reached-val ((m <NextWaypointResult>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader nav_apf_smach-msg:goal_reached-val is deprecated.  Use nav_apf_smach-msg:goal_reached instead.")
  (goal_reached m))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <NextWaypointResult>) ostream)
  "Serializes a message object of type '<NextWaypointResult>"
  (roslisp-msg-protocol:serialize (cl:slot-value msg 'next_waypoint) ostream)
  (cl:write-byte (cl:ldb (cl:byte 8 0) (cl:if (cl:slot-value msg 'goal_reached) 1 0)) ostream)
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <NextWaypointResult>) istream)
  "Deserializes a message object of type '<NextWaypointResult>"
  (roslisp-msg-protocol:deserialize (cl:slot-value msg 'next_waypoint) istream)
    (cl:setf (cl:slot-value msg 'goal_reached) (cl:not (cl:zerop (cl:read-byte istream))))
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<NextWaypointResult>)))
  "Returns string type for a message object of type '<NextWaypointResult>"
  "nav_apf_smach/NextWaypointResult")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'NextWaypointResult)))
  "Returns string type for a message object of type 'NextWaypointResult"
  "nav_apf_smach/NextWaypointResult")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<NextWaypointResult>)))
  "Returns md5sum for a message object of type '<NextWaypointResult>"
  "dc767de33709a7aaa6304200bd40705d")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'NextWaypointResult)))
  "Returns md5sum for a message object of type 'NextWaypointResult"
  "dc767de33709a7aaa6304200bd40705d")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<NextWaypointResult>)))
  "Returns full string definition for message of type '<NextWaypointResult>"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%# Result: siguiente waypoint y si ya se alcanzó el destino~%geometry_msgs/PoseStamped next_waypoint~%bool goal_reached~%~%================================================================================~%MSG: geometry_msgs/PoseStamped~%# A Pose with reference coordinate frame and timestamp~%Header header~%Pose pose~%~%================================================================================~%MSG: std_msgs/Header~%# Standard metadata for higher-level stamped data types.~%# This is generally used to communicate timestamped data ~%# in a particular coordinate frame.~%# ~%# sequence ID: consecutively increasing ID ~%uint32 seq~%#Two-integer timestamp that is expressed as:~%# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')~%# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')~%# time-handling sugar is provided by the client library~%time stamp~%#Frame this data is associated with~%string frame_id~%~%================================================================================~%MSG: geometry_msgs/Pose~%# A representation of pose in free space, composed of position and orientation. ~%Point position~%Quaternion orientation~%~%================================================================================~%MSG: geometry_msgs/Point~%# This contains the position of a point in free space~%float64 x~%float64 y~%float64 z~%~%================================================================================~%MSG: geometry_msgs/Quaternion~%# This represents an orientation in free space in quaternion form.~%~%float64 x~%float64 y~%float64 z~%float64 w~%~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'NextWaypointResult)))
  "Returns full string definition for message of type 'NextWaypointResult"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%# Result: siguiente waypoint y si ya se alcanzó el destino~%geometry_msgs/PoseStamped next_waypoint~%bool goal_reached~%~%================================================================================~%MSG: geometry_msgs/PoseStamped~%# A Pose with reference coordinate frame and timestamp~%Header header~%Pose pose~%~%================================================================================~%MSG: std_msgs/Header~%# Standard metadata for higher-level stamped data types.~%# This is generally used to communicate timestamped data ~%# in a particular coordinate frame.~%# ~%# sequence ID: consecutively increasing ID ~%uint32 seq~%#Two-integer timestamp that is expressed as:~%# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')~%# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')~%# time-handling sugar is provided by the client library~%time stamp~%#Frame this data is associated with~%string frame_id~%~%================================================================================~%MSG: geometry_msgs/Pose~%# A representation of pose in free space, composed of position and orientation. ~%Point position~%Quaternion orientation~%~%================================================================================~%MSG: geometry_msgs/Point~%# This contains the position of a point in free space~%float64 x~%float64 y~%float64 z~%~%================================================================================~%MSG: geometry_msgs/Quaternion~%# This represents an orientation in free space in quaternion form.~%~%float64 x~%float64 y~%float64 z~%float64 w~%~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <NextWaypointResult>))
  (cl:+ 0
     (roslisp-msg-protocol:serialization-length (cl:slot-value msg 'next_waypoint))
     1
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <NextWaypointResult>))
  "Converts a ROS message object to a list"
  (cl:list 'NextWaypointResult
    (cl:cons ':next_waypoint (next_waypoint msg))
    (cl:cons ':goal_reached (goal_reached msg))
))
