// Auto-generated. Do not edit!

// (in-package nav_apf_smach.msg)


"use strict";

const _serializer = _ros_msg_utils.Serialize;
const _arraySerializer = _serializer.Array;
const _deserializer = _ros_msg_utils.Deserialize;
const _arrayDeserializer = _deserializer.Array;
const _finder = _ros_msg_utils.Find;
const _getByteLength = _ros_msg_utils.getByteLength;

//-----------------------------------------------------------

class DriveToPoseFeedback {
  constructor(initObj={}) {
    if (initObj === null) {
      // initObj === null is a special case for deserialization where we don't initialize fields
      this.remaining_distance = null;
    }
    else {
      if (initObj.hasOwnProperty('remaining_distance')) {
        this.remaining_distance = initObj.remaining_distance
      }
      else {
        this.remaining_distance = 0.0;
      }
    }
  }

  static serialize(obj, buffer, bufferOffset) {
    // Serializes a message object of type DriveToPoseFeedback
    // Serialize message field [remaining_distance]
    bufferOffset = _serializer.float32(obj.remaining_distance, buffer, bufferOffset);
    return bufferOffset;
  }

  static deserialize(buffer, bufferOffset=[0]) {
    //deserializes a message object of type DriveToPoseFeedback
    let len;
    let data = new DriveToPoseFeedback(null);
    // Deserialize message field [remaining_distance]
    data.remaining_distance = _deserializer.float32(buffer, bufferOffset);
    return data;
  }

  static getMessageSize(object) {
    return 4;
  }

  static datatype() {
    // Returns string type for a message object
    return 'nav_apf_smach/DriveToPoseFeedback';
  }

  static md5sum() {
    //Returns md5sum for a message object
    return 'af85e6a5c9030f385c968a48eaafb15c';
  }

  static messageDefinition() {
    // Returns full string definition for message
    return `
    # ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======
    # Feedback
    float32 remaining_distance
    
    
    `;
  }

  static Resolve(msg) {
    // deep-construct a valid message object instance of whatever was passed in
    if (typeof msg !== 'object' || msg === null) {
      msg = {};
    }
    const resolved = new DriveToPoseFeedback(null);
    if (msg.remaining_distance !== undefined) {
      resolved.remaining_distance = msg.remaining_distance;
    }
    else {
      resolved.remaining_distance = 0.0
    }

    return resolved;
    }
};

module.exports = DriveToPoseFeedback;
